name: DockerBuildPush

on:
  push:
    branches: [ functionland/fula,Build-workflow ]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ORG_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./docker/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USER }}/sugarfunge-node:latest
